"""empty message

Revision ID: 3840a888dd60
Revises: 73aec3554620
Create Date: 2020-05-06 18:40:07.182603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3840a888dd60'
down_revision = '73aec3554620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case', 'params')
    op.add_column('report', sa.Column('name', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'report', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report', type_='unique')
    op.drop_column('report', 'name')
    op.add_column('case', sa.Column('params', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
