"""empty message

Revision ID: 3c5426b169ce
Revises: 
Create Date: 2020-05-06 13:52:41.093797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5426b169ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('is_exe', sa.Enum('yes', 'no'), nullable=True),
    sa.Column('method', sa.Enum('get', 'post'), nullable=True),
    sa.Column('headers', sa.String(length=200), nullable=True),
    sa.Column('params', sa.String(length=200), nullable=True),
    sa.Column('data', sa.String(length=500), nullable=True),
    sa.Column('expect_code', sa.Integer(), nullable=True),
    sa.Column('expect_return', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Enum('1', '2'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(length=100000), nullable=True),
    sa.Column('create_time', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('case')
    # ### end Alembic commands ###
