"""empty message

Revision ID: 73aec3554620
Revises: bd5c1218c43d
Create Date: 2020-05-06 14:07:51.306276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73aec3554620'
down_revision = 'bd5c1218c43d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('url', sa.String(length=80), nullable=True),
    sa.Column('is_exe', sa.Enum('yes', 'no'), nullable=True),
    sa.Column('method', sa.Enum('get', 'post'), nullable=True),
    sa.Column('headers', sa.String(length=200), nullable=True),
    sa.Column('params', sa.String(length=200), nullable=True),
    sa.Column('data', sa.String(length=500), nullable=True),
    sa.Column('expect_code', sa.Integer(), nullable=True),
    sa.Column('expect_return', sa.String(length=500), nullable=True),
    sa.Column('level', sa.Enum('1', '2'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(length=300000), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('case')
    # ### end Alembic commands ###
