"""empty message

Revision ID: 7677ddedabd0
Revises: 3840a888dd60
Create Date: 2020-05-06 19:56:45.376828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7677ddedabd0'
down_revision = '3840a888dd60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('based_url', sa.String(length=80), nullable=True),
    sa.Column('based_headers', sa.String(length=500), nullable=True),
    sa.Column('cookie', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
