"""empty message

Revision ID: bd5c1218c43d
Revises: 3c5426b169ce
Create Date: 2020-05-06 14:03:58.987155

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd5c1218c43d'
down_revision = '3c5426b169ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_index('name', table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('is_exe', mysql.ENUM('yes', 'no'), nullable=True),
    sa.Column('method', mysql.ENUM('get', 'post'), nullable=True),
    sa.Column('headers', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('params', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('data', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('expect_code', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('expect_return', mysql.VARCHAR(length=500), nullable=True),
    sa.Column('level', mysql.ENUM('1', '2'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'case', ['name'], unique=True)
    op.create_table('report',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('content', mysql.MEDIUMTEXT(), nullable=True),
    sa.Column('create_time', mysql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
